services:
    laravel:
        build:
            context: "./.devcontainer"
            dockerfile: "Dockerfile"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        # ports:
        #     - '${APP_PORT:-80}:80'
        #     - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        # environment:
        #     XDEBUG_MODE: 'develop,debug'
        #     XDEBUG_CONFIG: 'client_host=127.0.0.1'
        command: 
            - "/usr/local/bin/php"
            - "-d"
            - "xdebug.mode=develop,debug"
            - "/var/www/html/artisan"
            - "serve"
            - "--host=0.0.0.0"
            - "--port=80"
        volumes:
            - '.:/var/www/html'
            - '/var/run/docker.sock:/var/run/docker.sock'
        depends_on:
            - pgsql
            - redis
            - memcached
            - mailpit
            - selenium
    pgsql:
        image: 'postgres:17'
        environment:
            PGPASSWORD: 'secret'
            POSTGRES_DB: 'laravel'
            POSTGRES_USER: 'laravel'
            POSTGRES_PASSWORD: 'secret'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - 'laravel'
                - '-U'
                - 'laravel'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        volumes:
            - 'redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    memcached:
        image: 'memcached:alpine'
    mailpit:
        image: 'axllent/mailpit:latest'
        # ports:
        #     - '127.0.0.1:8025:8025'
    selenium:
        image: selenium/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
    influxdb:
        image: 'influxdb:2.7-alpine'
        environment:
            DOCKER_INFLUXDB_INIT_MODE: 'setup'
            DOCKER_INFLUXDB_INIT_USERNAME: 'laravel'
            DOCKER_INFLUXDB_INIT_PASSWORD: 'secret'
            DOCKER_INFLUXDB_INIT_ORG: 'laravel'
            DOCKER_INFLUXDB_INIT_BUCKET: 'laravel'
volumes:
    pgsql:
        driver: local
    redis:
        driver: local
    influxdb:
        driver: local
